name: CI Build

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  test:
    name: Tests
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['18', '20', '22']

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
